add sanitized branch config
add branch configuration, along with tag and latest push

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,8 +1,4 @@
 version: 2.1
-orbs:
-  # Add your new orb
-  docker-buildx: devarsh/docker-buildx-orb@dev:test
-
 executors:
   docker-executor:
     docker:
@@ -20,30 +16,26 @@ jobs:
       - checkout
       - setup_remote_docker:
           version: 20.10.24
-      - docker-buildx/install
-      
       - run:
-          name: Check if Docker image tag exists
+          name: Build and Push Docker tag Image
           command: |
             # Set environment variables
             IMAGE_TAG=$CIRCLE_TAG
-            # I thought, this will be the best place to put this variable
-            IMAGE_NAME=$CIRCLE_PROJECT_NAME
 
             # Check if the Docker image with the same tag already exists in Docker Hub
-            if curl -s -f -u "$DOCKERHUB_USERNAME":"$DOCKERHUB_PASSWORD" "https://hub.docker.com/v2/repositories/devarsh10/ph-ee-connector-ams-mifos/tags/$IMAGE_TAG" > /dev/null; then
+            if curl -s -f -u "$DOCKERHUB_USERNAME":"$DOCKERHUB_PASSWORD" "https://hub.docker.com/v2/repositories/openmf/ph-ee-connector-ams-mifos/tags/$IMAGE_TAG" > /dev/null; then
               echo "Skipping the build and push as the tag $IMAGE_TAG already exists in Docker Hub."
               exit 0
             fi
-      
-      - run:
-          name: Build Application
-          command: ./gradlew bootJar
-          
-      - docker-buildx/build-and-push:
-          # image-name: "devarsh10/ph-ee-connector-ams-mifos" configure this variable in CircleCI
-          image-name: $CIRCLE_PROJECT_NAME
-          tag: $CIRCLE_TAG
+
+            # Build and tag the Docker image
+            ./gradlew bootJar
+            docker build -t "openmf/ph-ee-connector-ams-mifos:$IMAGE_TAG" .
+
+            # Push the Docker image to Docker Hub
+            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
+            docker push "openmf/ph-ee-connector-ams-mifos:$IMAGE_TAG"
+
           # when: always  # The job will be executed even if there's no match for the tag filter
 
   build_and_push_latest_image:
@@ -57,35 +49,42 @@ jobs:
       # Install Docker to build and push the image
       - setup_remote_docker:
           version: 20.10.24
-      - docker-buildx/install
 
+      # Build the Docker image
       - run:
-          name: Build Application
+          name: Build Docker image
           command: |
+            #Check for PR title Validity
+
+            IMAGE_TAG=$CIRCLE_TAG
             ./gradlew checkstyleMain
             ./gradlew clean bootJar
-            
-      - docker-buildx/build-and-push:
-          image-name: $CIRCLE_PROJECT_NAME
-          tag: "latest"
-      # # Log in to DockerHub using environment variables
-      # - run:
-      #     name: Login to DockerHub
-      #     command: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
+            docker build -t openmf/ph-ee-connector-ams-mifos:latest .
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
+              docker image tag openmf/$CIRCLE_PR_REPONAME:latest openmf/$CIRCLE_PR_REPONAME:$JIRA_STORY
+            fi
+      # Log in to DockerHub using environment variables
+      - run:
+          name: Login to DockerHub
+          command: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
 
-      # # Push the Docker image to DockerHub
-      # - run:
-      #     name: Push Docker image to DockerHub
-      #     command: |
-      #       if [ "$CIRCLE_BRANCH" = "master" ]; then
-      #       docker push openmf/ph-ee-connector-ams-mifos:latest
-      #       fi
-      #       if [ "$CIRCLE_BRANCH" != "master" ]; then
-      #       PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
-      #       PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
-      #       JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
-      #       docker push openmf/$CIRCLE_PR_REPONAME:${JIRA_STORY}
-      #       fi
+      # Push the Docker image to DockerHub
+      - run:
+          name: Push Docker image to DockerHub
+          command: |
+            if [ "$CIRCLE_BRANCH" = "master" ]; then
+            docker push openmf/ph-ee-connector-ams-mifos:latest
+            fi
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
+            PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+            PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+            JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+            docker push openmf/$CIRCLE_PR_REPONAME:${JIRA_STORY}
+            fi
 workflows:
   version: 2
   build-and-push:
